//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khazan_DataEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khazan_DataEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增一项.
        /// </summary>
        public static string AddNewDataItem {
            get {
                return ResourceManager.GetString("AddNewDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动保存.
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消置顶.
        /// </summary>
        public static string CancelTop {
            get {
                return ResourceManager.GetString("CancelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 克隆.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含（包括字段）.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含（只有TIDX）.
        /// </summary>
        public static string Contains_Ori {
            get {
                return ResourceManager.GetString("Contains_Ori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成Pak.
        /// </summary>
        public static string Create_Pak {
            get {
                return ResourceManager.GetString("Create_Pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置数据.
        /// </summary>
        public static string DataContent {
            get {
                return ResourceManager.GetString("DataContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存该路径为默认保存位置.
        /// </summary>
        public static string DefaultSaveFolder {
            get {
                return ResourceManager.GetString("DefaultSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示源数据.
        /// </summary>
        public static string DisplayOld {
            get {
                return ResourceManager.GetString("DisplayOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 友情赞助及教程.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请拖拽一个文件夹.
        /// </summary>
        public static string DragFolder {
            get {
                return ResourceManager.GetString("DragFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全字匹配.
        /// </summary>
        public static string ExactMatch {
            get {
                return ResourceManager.GetString("ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出备注.
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解包Pak.
        /// </summary>
        public static string Extract_Pak {
            get {
                return ResourceManager.GetString("Extract_Pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索文件.
        /// </summary>
        public static string FileSearch {
            get {
                return ResourceManager.GetString("FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一次保存，请选择一个Mod文件夹用于保存修改后的数据.
        /// </summary>
        public static string FirstSave {
            get {
                return ResourceManager.GetString("FirstSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局搜索.
        /// </summary>
        public static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入备注.
        /// </summary>
        public static string ImportDesc {
            get {
                return ResourceManager.GetString("ImportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索TIDX或备注.
        /// </summary>
        public static string ItemSearch {
            get {
                return ResourceManager.GetString("ItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开所在文件夹.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源数据.
        /// </summary>
        public static string OriginData {
            get {
                return ResourceManager.GetString("OriginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正则.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存备注成功.
        /// </summary>
        public static string SaveDescSuss {
            get {
                return ResourceManager.GetString("SaveDescSuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索结果.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择Data数据文件夹.
        /// </summary>
        public static string SelectDataFolder {
            get {
                return ResourceManager.GetString("SelectDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择导入备注的文件夹.
        /// </summary>
        public static string SelectImportDesc {
            get {
                return ResourceManager.GetString("SelectImportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡赞配表编辑器.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中对应条目的右键置顶此区域.
        /// </summary>
        public static string TopHere {
            get {
                return ResourceManager.GetString("TopHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通配符.
        /// </summary>
        public static string Wildcard {
            get {
                return ResourceManager.GetString("Wildcard", resourceCulture);
            }
        }
    }
}
